import { Transaction, Alert, Case, UserRiskProfile, FraudRule, SystemSetting } from '../types';

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'TXN-9842-A1',
    transaction_id: 'TXN-9842-A1',
    user_id: 'USR-CUST-1001',
    user_name: 'John Doe',
    merchant_id: 'MERCH-AMAZON',
    merchant_name: 'Amazon Web Retail',
    merchant_category: 'Electronics & Retail',
    payment_method: 'CREDIT_CARD',
    transaction_type: 'PURCHASE',
    amount: 1450.00,
    currency: 'USD',
    device_id: 'DEV-MACBOOK-01',
    ip_address: '198.51.100.45',
    city: 'London',
    country: 'GB',
    failed_attempts: 0,
    source: 'API',
    risk_score: 84,
    risk_level: 'CRITICAL',
    ml_anomaly_score: 0.88,
    rules_triggered: [
      { rule_id: 'RULE-001', rule_name: 'Velocity Spike', severity: 'CRITICAL', category: 'VELOCITY', points: 35, version: '1.0' },
      { rule_id: 'RULE-004', rule_name: 'High Amount Cross-Border', severity: 'HIGH', category: 'AMOUNT', points: 25, version: '1.0' }
    ],
    risk_factors: [
      { factor_name: 'Excessive Amount', weight: 0.4, score: 85, contribution: 34, description: 'High amount exceeding 3x 30-day baseline' },
      { factor_name: 'New Geo', weight: 0.3, score: 80, contribution: 24, description: 'Cross-border transaction without prior geo fingerprint' }
    ],
    status: 'DECLINED',
    timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
  {
    id: 'TXN-9843-B2',
    transaction_id: 'TXN-9843-B2',
    user_id: 'USR-CUST-1002',
    user_name: 'Sarah Connor',
    merchant_id: 'MERCH-BINANCE',
    merchant_name: 'Binance Global Exchange',
    merchant_category: 'Crypto & Exchange',
    payment_method: 'CRYPTO',
    transaction_type: 'TRANSFER',
    amount: 3200.00,
    currency: 'USD',
    device_id: 'DEV-IPHONE-02',
    ip_address: '203.0.113.88',
    city: 'Singapore',
    country: 'SG',
    failed_attempts: 2,
    source: 'API',
    risk_score: 72,
    risk_level: 'HIGH',
    ml_anomaly_score: 0.76,
    rules_triggered: [
      { rule_id: 'RULE-002', rule_name: 'Crypto High Risk Tier', severity: 'HIGH', category: 'MERCHANT', points: 25, version: '1.0' }
    ],
    risk_factors: [
      { factor_name: 'Merchant Risk', weight: 0.4, score: 75, contribution: 30, description: 'High risk merchant category' },
      { factor_name: 'Failed PIN Attempts', weight: 0.3, score: 70, contribution: 21, description: 'Multiple failed PIN attempts prior to authorization' }
    ],
    status: 'FLAGGED',
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'TXN-9844-C3',
    transaction_id: 'TXN-9844-C3',
    user_id: 'USR-CUST-1003',
    user_name: 'Alice Smith',
    merchant_id: 'MERCH-APPLE',
    merchant_name: 'Apple Store Online',
    merchant_category: 'Electronics & Devices',
    payment_method: 'APPLE_PAY',
    transaction_type: 'PURCHASE',
    amount: 199.00,
    currency: 'USD',
    device_id: 'DEV-IPHONE-15',
    ip_address: '192.0.2.14',
    city: 'Cupertino',
    country: 'US',
    failed_attempts: 0,
    source: 'MOBILE_APP',
    risk_score: 12,
    risk_level: 'LOW',
    ml_anomaly_score: 0.10,
    rules_triggered: [],
    risk_factors: [],
    status: 'APPROVED',
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'TXN-9845-D4',
    transaction_id: 'TXN-9845-D4',
    user_id: 'USR-CUST-1004',
    user_name: 'Elena Rostova',
    merchant_id: 'MERCH-UBER',
    merchant_name: 'Uber BV Amsterdam',
    merchant_category: 'Transportation',
    payment_method: 'CREDIT_CARD',
    transaction_type: 'PURCHASE',
    amount: 42.50,
    currency: 'EUR',
    device_id: 'DEV-ANDROID-09',
    ip_address: '185.220.101.5',
    city: 'Amsterdam',
    country: 'NL',
    failed_attempts: 0,
    source: 'API',
    risk_score: 18,
    risk_level: 'LOW',
    ml_anomaly_score: 0.15,
    rules_triggered: [],
    risk_factors: [],
    status: 'APPROVED',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'TXN-9846-E5',
    transaction_id: 'TXN-9846-E5',
    user_id: 'USR-CUST-1005',
    user_name: 'Marcus Vance',
    merchant_id: 'MERCH-DELIVEROO',
    merchant_name: 'Deliveroo London',
    merchant_category: 'Food & Dining',
    payment_method: 'DEBIT_CARD',
    transaction_type: 'PURCHASE',
    amount: 58.00,
    currency: 'GBP',
    device_id: 'DEV-IPHONE-08',
    ip_address: '82.165.197.1',
    city: 'London',
    country: 'GB',
    failed_attempts: 0,
    source: 'MOBILE_APP',
    risk_score: 8,
    risk_level: 'LOW',
    ml_anomaly_score: 0.05,
    rules_triggered: [],
    risk_factors: [],
    status: 'APPROVED',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'TXN-9847-F6',
    transaction_id: 'TXN-9847-F6',
    user_id: 'USR-CUST-1006',
    user_name: 'Tariq Al-Mansoor',
    merchant_id: 'MERCH-TARGET',
    merchant_name: 'Target Stores US',
    merchant_category: 'Retail Goods',
    payment_method: 'CREDIT_CARD',
    transaction_type: 'PURCHASE',
    amount: 890.00,
    currency: 'USD',
    device_id: 'DEV-WINDOWS-04',
    ip_address: '64.233.160.1',
    city: 'Chicago',
    country: 'US',
    failed_attempts: 1,
    source: 'WEB_PORTAL',
    risk_score: 48,
    risk_level: 'MEDIUM',
    ml_anomaly_score: 0.45,
    rules_triggered: [
      { rule_id: 'RULE-005', rule_name: 'New Device Association', severity: 'MEDIUM', category: 'DEVICE', points: 15, version: '1.0' }
    ],
    risk_factors: [
      { factor_name: 'Device Anomaly', weight: 0.3, score: 50, contribution: 15, description: 'Unregistered device fingerprint detected' }
    ],
    status: 'APPROVED',
    timestamp: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
  }
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'ALT-1001-CRIT',
    title: 'High Velocity Transfer Spike on New Device',
    severity: 'CRITICAL',
    status: 'OPEN',
    alert_reason: 'Account USR-CUST-1001 triggered 3 high amount transactions within 90 seconds from an unrecognized IP in London.',
    transaction_id: 'TXN-9842-A1',
    risk_score: 84,
    triggered_rules: ['RULE-001', 'RULE-004'],
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    assigned_to: 'analyst@fraudshield.io'
  },
  {
    id: 'ALT-1002-HIGH',
    title: 'Suspicious Crypto Gateway Settlement',
    severity: 'HIGH',
    status: 'INVESTIGATING',
    alert_reason: 'Rapid outflow to high-risk merchant category following multiple authentication attempts.',
    transaction_id: 'TXN-9843-B2',
    risk_score: 72,
    triggered_rules: ['RULE-002'],
    created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    assigned_to: 'analyst@fraudshield.io'
  },
  {
    id: 'ALT-1003-MED',
    title: 'Unrecognized Device Association with Elevated Amount',
    severity: 'MEDIUM',
    status: 'OPEN',
    alert_reason: 'First time purchase from Windows workstation above average spending threshold.',
    transaction_id: 'TXN-9847-F6',
    risk_score: 48,
    triggered_rules: ['RULE-005'],
    created_at: new Date(Date.now() - 1000 * 60 * 145).toISOString(),
  }
];

export const MOCK_CASES: Case[] = [
  {
    id: 'CASE-2026-089',
    case_id: 'CASE-2026-089',
    title: 'Coordinated Account Takeover Attack Ring',
    description: 'Investigation into linked credential stuffing patterns affecting multiple retail accounts across London and Amsterdam.',
    status: 'INVESTIGATING',
    severity: 'CRITICAL',
    assigned_analyst: 'analyst@fraudshield.io',
    assigned_to: 'analyst@fraudshield.io',
    risk_score: 88,
    related_transaction_ids: ['TXN-9842-A1'],
    related_alert_ids: ['ALT-1001-CRIT'],
    alerts_count: 4,
    transactions_count: 6,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: 'CASE-2026-088',
    case_id: 'CASE-2026-088',
    title: 'Crypto Off-Ramping Anomaly Cluster',
    description: 'Review of merchant gateway transactions exhibiting high card testing frequency and rapid cashout attempts.',
    status: 'OPEN',
    severity: 'HIGH',
    assigned_analyst: 'analyst@fraudshield.io',
    assigned_to: 'analyst@fraudshield.io',
    risk_score: 74,
    related_transaction_ids: ['TXN-9843-B2'],
    related_alert_ids: ['ALT-1002-HIGH'],
    alerts_count: 2,
    transactions_count: 3,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  }
];

export const MOCK_RISK_PROFILES: UserRiskProfile[] = [
  {
    user_id: 'USR-CUST-1001',
    user_name: 'John Doe',
    profile_state: 'ESTABLISHED',
    total_transactions: 48,
    successful_transactions: 46,
    failed_transactions: 2,
    total_volume: 8400,
    avg_amount: 175,
    median_amount: 150,
    min_amount: 15,
    max_amount: 1450,
    std_dev_amount: 45,
    failure_rate: 0.04,
    typical_hours: [9, 14, 18],
    top_locations: [{ city: 'London', country: 'GB', count: 48 }],
    distinct_devices_count: 2,
    distinct_devices: ['DEV-MACBOOK-01'],
    distinct_merchants_count: 8,
    distinct_merchants: ['Amazon Web Retail'],
    contextual_signals: [],
    risk_level: 'HIGH',
    last_known_risk_score: 78,
    updated_at: new Date().toISOString(),
  },
  {
    user_id: 'USR-CUST-1002',
    user_name: 'Sarah Connor',
    profile_state: 'ESTABLISHED',
    total_transactions: 112,
    successful_transactions: 105,
    failed_transactions: 7,
    total_volume: 24500,
    avg_amount: 218,
    median_amount: 180,
    min_amount: 25,
    max_amount: 3200,
    std_dev_amount: 85,
    failure_rate: 0.06,
    typical_hours: [10, 16, 22],
    top_locations: [{ city: 'Singapore', country: 'SG', count: 112 }],
    distinct_devices_count: 3,
    distinct_devices: ['DEV-IPHONE-02'],
    distinct_merchants_count: 15,
    distinct_merchants: ['Binance Global Exchange'],
    contextual_signals: [],
    risk_level: 'CRITICAL',
    last_known_risk_score: 85,
    updated_at: new Date().toISOString(),
  },
  {
    user_id: 'USR-CUST-1003',
    user_name: 'Alice Smith',
    profile_state: 'ESTABLISHED',
    total_transactions: 65,
    successful_transactions: 65,
    failed_transactions: 0,
    total_volume: 5200,
    avg_amount: 80,
    median_amount: 65,
    min_amount: 10,
    max_amount: 350,
    std_dev_amount: 25,
    failure_rate: 0.0,
    typical_hours: [8, 12, 17],
    top_locations: [{ city: 'Cupertino', country: 'US', count: 65 }],
    distinct_devices_count: 1,
    distinct_devices: ['DEV-IPHONE-15'],
    distinct_merchants_count: 12,
    distinct_merchants: ['Apple Store Online'],
    contextual_signals: [],
    risk_level: 'LOW',
    last_known_risk_score: 14,
    updated_at: new Date().toISOString(),
  }
];

export const MOCK_RULES: FraudRule[] = [
  {
    id: 'RULE-001',
    name: 'High Velocity Spike Detection',
    description: 'Flags more than 3 transactions occurring within a 2-minute rolling window.',
    category: 'VELOCITY',
    severity: 'CRITICAL',
    weight: 35,
    priority: 1,
    is_active: true,
    condition_config: { velocity_count_2m: '> 3' },
    version: '1.2.0',
    created_by: 'admin@fraudshield.io',
    updated_by: 'admin@fraudshield.io',
  },
  {
    id: 'RULE-002',
    name: 'Crypto High Risk Merchant Outflow',
    description: 'Applies elevated risk weighting for transactions routed through crypto exchanges without verified device profile.',
    category: 'MERCHANT',
    severity: 'HIGH',
    weight: 25,
    priority: 2,
    is_active: true,
    condition_config: { merchant_category: 'Crypto & Exchange' },
    version: '1.0.0',
    created_by: 'admin@fraudshield.io',
    updated_by: 'admin@fraudshield.io',
  },
  {
    id: 'RULE-003',
    name: 'Cross-Border Geo-Hop Impossibility',
    description: 'Triggers when transaction originates from a location requiring impossible travel speed from previous session.',
    category: 'GEOGRAPHY',
    severity: 'CRITICAL',
    weight: 45,
    priority: 1,
    is_active: true,
    condition_config: { geo_speed_kmh: '> 850' },
    version: '2.1.0',
    created_by: 'admin@fraudshield.io',
    updated_by: 'admin@fraudshield.io',
  }
];

export const MOCK_SYSTEM_SETTINGS: SystemSetting[] = [
  {
    key: 'security.mfa_enforced',
    value: true,
    description: 'Requires TOTP MFA token on all administrative and analyst logins',
    updated_by: 'admin@fraudshield.io',
    updated_at: new Date().toISOString()
  },
  {
    key: 'pipeline.auto_decline_threshold',
    value: 80,
    description: 'Composite risk score threshold above which transactions are immediately blocked',
    updated_by: 'admin@fraudshield.io',
    updated_at: new Date().toISOString()
  },
  {
    key: 'pipeline.manual_review_threshold',
    value: 50,
    description: 'Risk score boundary for escalating transactions to the analyst triage queue',
    updated_by: 'admin@fraudshield.io',
    updated_at: new Date().toISOString()
  },
  {
    key: 'model.drift_detection_p_value',
    value: 0.05,
    description: 'Statistical significance limit for flagging data drift and triggering retraining recommendations',
    updated_by: 'admin@fraudshield.io',
    updated_at: new Date().toISOString()
  }
];

export function extractSafeArray<T>(data: any, fallback: T[] = []): T[] {
  if (Array.isArray(data)) return data;
  if (data && Array.isArray(data.items)) return data.items;
  if (data && Array.isArray(data.data)) return data.data;
  if (data && Array.isArray(data.results)) return data.results;
  return fallback;
}
